### ISSUE TITLE
Update `caikit-nlp` version to resolve caikit/caikit-nlp#237

### ISSUE THREAD

**Issue by kpouget** [opendatahub-io/caikit-tgis-serving#120]
The current version of `caikit-tgis-serving` exposes some GRPC function arguments (and services) in random order. Two examples:
![image](https://github.com/opendatahub-io/caikit-tgis-serving/assets/7559202/8a31cd10-532f-4d51-8ca1-831b40dc2cfb)
![image](https://github.com/opendatahub-io/caikit-tgis-serving/assets/7559202/ab1a1ce3-8d43-4233-b233-15b452449be0)

The critical part of it (random argument order) is already solved in caikit/caikit-nlp#237 `main`. PR is open to fix the service method order.

The `caikit-nlp` git ref should be updated before publishing the next release of `caikit-tgis-serving`.

**Comment by dtrifiro** [comment]
Closed by https://github.com/opendatahub-io/caikit-tgis-serving/pull/124
