### ISSUE TITLE
Add more  ServingRuntime examples

### ISSUE THREAD

**Issue by dtrifiro** [opendatahub-io/caikit-tgis-serving#121]
Add more `ServingRuntime` examples with:
- caikit standalone
- tgis standalone
- caikit+tgis

Anything I'm forgetting, @Xaenalt ?

**Comment by Xaenalt** [comment]
Doesn't look like it to me, I think that covers all the tunables PSAP was looking at cc @dagrayvid @kpouget

**Comment by kpouget** [comment]
yes, here is the full list of env values that I'm using:

```
PT2_COMPILE
DTYPE_STR
INFERENCE_PLUGIN_TGIS_MODEL_LOADING_TIMEOUT_MS
MODEL_LOADING_TIMEOUT_MS

DEPLOYMENT_FRAMEWORK
FLASH_ATTENTION
MAX_BATCH_SIZE
MAX_BATCH_WEIGHT
MAX_CONCURRENT_REQUESTS
MAX_NEW_TOKENS
MAX_PREFILL_WEIGHT
MAX_SEQUENCE_LENGTH
RUNTIME_GRPC_SERVER_THREAD_POOL_SIZE
TRUST_REMOTE_CODE
```

(@dagrayvid might be using a few others, like sharding)

and one hack that we had to use is this one, to extend the TGIS timeout:
```
      EXTENDED_TIMEOUT=20000
      sed -i 's/load_timeout: .*/load_timeout: '$EXTENDED_TIMEOUT'/' /caikit/config/caikit-tgis.template.yml
```

**Comment by dtrifiro** [comment]
https://github.com/opendatahub-io/caikit-tgis-serving/pull/186
