### ISSUE TITLE
Caikit + TGIS returns empty answer when using HTTP calls

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/caikit-tgis-serving#147]
While using the ServingRuntime definition from https://github.com/opendatahub-io/caikit-tgis-serving/pull/131/files#diff-94e62eddc4f3b075ea6c7d9eb86d45728d2c9ebb3c00ae43fd81863ccb6c01f9 which leverages on REST call (HTTP port 8080) I'm facing issues in getting the model answers. 

The query returns empty response. These are 2 example of REST calls I tried:

```
curl -d '{"model_id": "<model_name>","inputs": "At what temperature does water boil?"}' -insecure <ksvc_url>:8080/api/v1/task/text-generation
```
```
curl --json '{"model_id": "<model_name>","inputs": "At what temperature does water boil?"}' -insecure <ksvc_url>:8080/api/v1/task/text-generation
```

I also tried by getting the cluster CA secret and include it in the curl call like this:

1. `oc get secret -n openshift-ingress router-certs-default -o json | jq '.data."tls.crt"' | sed 's/"//g' | base64 -d > <filename>.crt `
2. `curl --json '{"model_id": "<model_name>","inputs": "At what temperature does water boil?"}' -insecure <ksvc_url>:8080/api/v1/task/text-generation --cacert <filename>.crt`

Is there anything wrong with the way I'm performing the call? Please notice that using the same ServingRuntime set to use gRPC port it works just fine

**Comment by bdattoma** [comment]
@dtrifiro ^^

**Comment by dtrifiro** [comment]
Hey @bdattoma, apparently @Xaenalt run into this yesterday, and already fixed it here: https://github.com/opendatahub-io/caikit-tgis-serving/commit/22c9ec121c250de6b0cfd28870b816ee4313b4c2. 

Apparentlty the presence of the name in the containerport was causing this error. If you created the inferenceservice/servingruntime yesterday without this patch, this is the issue. 

I re-created both of them and am able to query the service:

```console
$ curl -k --json '{
    "model_id": "flan-t5-small-caikit",
    "inputs": "What is 2 plus 2?"
}' https://flan-t5-small-caikit-predictor-caikit-tgis-new-http.apps.ods-qe-02.rhods.ccitredhat.com:443/api/v1/task/text-generation
{"generated_text": "a slender slender", "generated_tokens": 11, "finish_reason": "EOS_TOKEN", "producer_id": {"name": "Text Generation", "version": "0.1.0"}, "input_token_count": 7, "seed": null}
```

Closing this. Let me know if you have any other issues

**Comment by bdattoma** [comment]
great! it works indeed. Thank you

Please could you update the documentation in this repo?

**Comment by bdattoma** [comment]
is streaming available under HTTP? @dtrifiro

**Comment by dtrifiro** [comment]
It does work locally:

```console
$ curl -k -v --json '{                                                                                                                                                                                                                                    
    "model_id": "flan-t5-small-caikit",
    "inputs": "What is 2 plus 2?"
}' localhost:8080/api/v1/task/server-streaming-text-generation
```

or with httpie:

```bash
http localhost:8080/api/v1/task/server-streaming-text-generation  model_id=flan-t5-small inputs="At what temperature does Nitrogen boil?"
