### ISSUE TITLE
Caikit Standalone image/SR

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/caikit-tgis-serving#163]
Caikit standalone image/SR needs to be created. 
Several steps required:
- [x] Contribute the RH dockerfile upstream
- [ ] Sync upstream with odh repo
- [ ] Build the image and share the image here
- [ ] Add the SR and Inference Service to caikit-tgis-serving repo
- [ ] Communicate to QE and UI teams the new SR

**Comment by heyselbi** [comment]
Copying the progress on this from STORY of this issue:
Upstream PRs: 
- https://github.com/caikit/caikit-nlp/pull/210
- https://github.com/caikit/caikit-nlp/pull/216
- https://github.com/caikit/caikit-nlp/pull/244

**Comment by dtrifiro** [comment]
> Add the SR and Inference Service to caikit-tgis-serving repo

Does that even belong there? caikit standalone does not use tgis at all

> Build the image and share the image here

I guess the only step required for that is adding CI to build the image, the upstream version should be ok. Regarding CI, do we want to use openshift or gha?

**Comment by dtrifiro** [comment]
Build definition PR submitted here https://github.com/openshift/release/pull/46224

**Comment by dtrifiro** [comment]
Even if not planned, example  manifests have been merged here: https://github.com/opendatahub-io/caikit-tgis-serving/pull/186
