### ISSUE TITLE
[SPIKE] Impact of TGIS's new req on safetensor format

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/caikit-tgis-serving#33]

**Comment by Xaenalt** [comment]
According to Nick Hill, it's just a narrowing of support of any PyTorch model to requiring the downloader to use the safetensor format. There are probably a few edge cases where this will come up, but I think overall not high in terms of impact

**Comment by Xaenalt** [comment]
After further clarification, it will affect more than their downloader, to quote:
> for certain kinds of models it will be needed (e.g. gpt-neox / t5 / llama, etc), at least if they are going to use the optimized code path and/or tensor parallel (multi-GPU)
