### ISSUE TITLE
Restructure and Enhance the QuickStart documentation

### ISSUE THREAD

**Issue by heyselbi** [opendatahub-io/caikit-tgis-serving#58]
The new documentation should have sections that answer the following questions:
- Installation Steps
- How do you add/deploy a model and a sample inference URL with a sample model in the example?
- Remove a model (undeploy)
- Canary rollout, A/B testing
- How to upgrade runtime?
- How to access metrics?

**Comment by heyselbi** [comment]
Draft PR: https://github.com/opendatahub-io/caikit-tgis-serving/pull/61

**Comment by heyselbi** [comment]
Melissa's PR: https://github.com/opendatahub-io/caikit-tgis-serving/pull/65/files

**Comment by bdattoma** [comment]
In the README.md there are links which bring to blank page with "TO DO" text. The 2 links are:
- https://github.com/opendatahub-io/caikit-tgis-serving/blob/main/demo/kserve/traffic-splitting.md
- https://github.com/opendatahub-io/caikit-tgis-serving/blob/main/demo/kserve/upgrade-runtime.md

What's the plan? Shall we leave these blank for the 5 Sept release? @heyselbi @MelissaFlinn

**Comment by heyselbi** [comment]
Closing the issue as the main restructuring is complete. Adding two follow up issues:
1) For two remaining sections: Update runtime and Traffic splitting ([issue](https://github.com/opendatahub-io/caikit-tgis-serving/issues/75))
2) Metrics docs need some clarification on how to obtain certain metrics ([issue](https://github.com/opendatahub-io/caikit-tgis-serving/issues/73))
