### ISSUE TITLE
Remove namespaces from demo/kserve/custom-manifests/metrics yamls

### ISSUE THREAD

**Issue by manosnoam** [opendatahub-io/caikit-tgis-serving#71]
In  https://github.com/opendatahub-io/caikit-tgis-serving/blob/main/demo/kserve/metrics.md

It is mentioned to use `-n $TEST_NS` for applying:
`custom-manifests/metrics/uwm-cm-enable.yaml` and `custom-manifests/metrics/uwm-cm-conf.yaml`

![image](https://github.com/opendatahub-io/caikit-tgis-serving/assets/9913945/ad20d306-b4b4-461b-a65e-2245cda1460a)

However, since the namespace was already defined in the yamls, it will fail with:

> $▶ oc apply -f ./custom-manifests/metrics/uwm-cm-enable.yaml -n $TEST_NS
> error: the namespace from the provided object "openshift-monitoring" does not match the namespace "kserve-demo".
> You must pass '--namespace=openshift-monitoring' to perform this operation.

Please update the yamls - and remove the namespace item, in order for above command to work.

Related feature: https://github.com/opendatahub-io/caikit/issues/3

**Comment by heyselbi** [comment]
Hi @manosnoam, sounds good. I will get it done by the end of this week and address all quickstart issues that came up in aggregate.
