### ISSUE TITLE
Metrics for caikit, tgi and istio were not observed in the deployed namespace

### ISSUE THREAD

**Issue by manosnoam** [opendatahub-io/caikit-tgis-serving#72]
After following instructions to deploy and access Metrics on RHODS 1.32 v2 RC7 (brew.registry.redhat.io/rh-osbs/iib:568805), according to:
https://github.com/opendatahub-io/caikit-tgis-serving/blob/main/demo/kserve/metrics.md
which involves applying 2 configmaps into a test namespace (for example TEST_NS=watsonx)

- https://github.com/opendatahub-io/caikit-tgis-serving/blob/main/demo/kserve/custom-manifests/metrics/uwm-cm-enable.yaml
- https://github.com/opendatahub-io/caikit-tgis-serving/blob/main/demo/kserve/custom-manifests/metrics/uwm-cm-conf.yaml

The configMaps were created in the test namespace:
![image](https://github.com/opendatahub-io/caikit-tgis-serving/assets/9913945/f9374210-fbf8-4564-81ce-df599e80499c)

```
$▶ oc describe configmap/cluster-monitoring-config -n ${TEST_NS}
Name:         cluster-monitoring-config
Namespace:    watsonx
Labels:       <none>
Annotations:  <none>

Data
====
config.yaml:
----
enableUserWorkload: true


BinaryData
====

Events:  <none>

$▶ oc describe configmap/user-workload-monitoring-config -n ${TEST_NS}
Name:         user-workload-monitoring-config
Namespace:    watsonx
Labels:       <none>
Annotations:  <none>

Data
====
config.yaml:
----
prometheus:
  logLevel: debug 
  retention: 15d #Change as needed


BinaryData
====

Events:  <none>
```

But the expected metrics for caikit, tgi or istio were not observed as expected:
![image](https://github.com/opendatahub-io/caikit-tgis-serving/assets/9913945/6b893a6a-e0cd-4d86-b148-4957ee7d8a8d)

Looking at the default namespace `openshift-monitoring` - we can see that the original configmap was not changed:

![image](https://github.com/opendatahub-io/caikit-tgis-serving/assets/9913945/af8a1e10-640a-4f27-b3e4-001ff56ccb82)

Apparently, if updating the default configmaps in `openshift-user-workload-monitoring` and in `cluster-monitoring-config` then the expected metrics show up.

Related feature: https://github.com/opendatahub-io/caikit/issues/3

**Comment by VedantMahabaleshwarkar** [comment]
@manosnoam Hey, does the script automatically deploy the UWM configmaps into the `TEST_NS`? If so that's an error in the install script. The actual yaml files `uwm-cm-conf.yaml` and `uwm-cm-enable.yaml` have the namespaces `openshift-user-workload-monitoring` and `openshift-monitoring` specified.
