### ISSUE TITLE
KServe does not catch Caikit runtime status correctly when subsprocess (tgis) have issues

### ISSUE THREAD

**Issue by kpouget** [opendatahub-io/caikit-tgis-serving#88]
When I create a ServingRuntime+InferenceService with some incorrect parameters, Caikit cannot load the model. 
```
{"channel": "MODEL-LOADER", "exception": null, "level": "error", "log_code": "<RUN62912924E>", "message": "load failed when processing path: /mnt/models/flan-t5-small-caikit with error: RuntimeError('TGIS failed to boot up with the model. See logs for details')", "model_id": "flan-t5-small-caikit", "num_indent": 0, "thread_id": 140660900353792, "timestamp": "2023-09-21T19:39:45.781105"}
```
This part is expected. However, the `InferenceService` still shows the model as `Loaded`, which is unexpected:
```
  modelStatus:
    copies:
      failedCopies: 0
      totalCopies: 1
    states:
      activeModelState: Loaded
      targetModelState: Loaded
    transitionStatus: UpToDate
```
* [InferenceService status](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_topsail/49/pull-ci-openshift-psap-topsail-main-watsonx-serving-light/1704936282028773376/artifacts/light/test/artifacts/000__local_ci__run_multi_deploy/ci-pods_artifacts/ci-pod-1/000__deploy_flan-t5-small-cpu/002__watsonx_serving__deploy_model/artifacts/inference_service.yaml)
* [predictor deployment logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_topsail/49/pull-ci-openshift-psap-topsail-main-watsonx-serving-light/1704936282028773376/artifacts/light/gather-extra/artifacts/pods/watsonx-e2e-0-flan-t5-small-cpu_flan-t5-small-cpu-predictor-00001-deployment-586d99fdd5-mjrmg_kserve-container.log)
* [RH-internal slack discussion](https://redhat-internal.slack.com/archives/C05742W6F7T/p1695326975999609)

**Comment by kpouget** [comment]
I see that many `text-generation` process remains `<defunct>`  when the serving runtime is running after it hit this error:
```
sh-5.1$ ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1000850+       1  0.5  0.0 19143780 611752 ?     Ssl  09:02   0:07 python3 -m caikit.runtime.grpc_server
1000850+     401  0.0  0.0      0     0 ?        Z    09:03   0:01 [text-generation] <defunct>
1000850+     403  0.0  0.0      0     0 ?        Z    09:03   0:01 [text-generation] <defunct>
1000850+     405  0.0  0.0      0     0 ?        Z    09:03   0:00 [text-generation] <defunct>
```

this means that Python `caikit.runtime.grpc_server` process does not `wait()` for the `text-generation`. This explains why it doesn't detect that `text-generation` failed ...

**Comment by Xaenalt** [comment]
This should be handled by the container splitting (this sprint)

**Comment by dtrifiro** [comment]
When running `caikit`+`tgis` in [this](https://github.com/opendatahub-io/caikit-tgis-serving/blob/9d21c6f65d27d2005a210355bdaf6360c32e430b/docs/caikit-servingruntime.yaml) configuration, this is no longer an issue.

**Comment by kpouget** [comment]
@dtrifiro what about when running caikit+tgis in the single container? 🤔

**Comment by Xaenalt** [comment]
Single container architecture was only a stopgap to the current architecture

**Comment by lugi0** [comment]
Verified in RHOAI 2.5 RC4, now if I cause a failure while loading a model (i.e. give the wrong path to the deployment modal) the InferenceService will set the `modelStatus` to `FailedToLoad` with relevant error messages.
