### ISSUE TITLE
Create a list of package requirements

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/caikit-tgis-serving#89]
Using the latest version https://github.com/opendatahub-io/caikit-tgis-serving/blob/main/demo/kserve/scripts/generate-wildcard-certs.sh the script is failing with the following error:

```
+ openssl req -x509 -newkey rsa:2048 -sha256 -days 3560 -nodes -subj '/CN=<value>' -extensions san -config <configpath> -CA <cert_path> -CAkey <key_path> -keyout <keyout_path> -out <out_path>
req: Unrecognized flag CA
req: Use -help for summary.
```

The cause was due an outdated pkg installed on the system. It could happen to anyone using the script, hence it would be good to explicitly say the minimum reqs

**Comment by chtyler** [comment]
@heyselbi @bdattoma  - Did you intend for this bug to be included as a known issue in the 1.33 release notes, or did you include the documentation solely to document the minimum package requirements for running the script?

**Comment by heyselbi** [comment]
Hi @chtyler , added the doc label because the issue is related to the quickstart we have in this repo. The quickstart instructs the user to execute a script that has a bug Berto mentioned.

**Comment by chtyler** [comment]
Thanks Selbi, I can confirm that I will not include this bug in the 1.33 release notes.

**Comment by Xaenalt** [comment]
This step is no longer necessary, it is handled by the operator now. The manual install steps are officially legacy with 2.5
